# Change these first
owner: krachim # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Koelner Institut
    url: https://ilias.koelner-institut.de
  - name: Holzauge Fotografie
    url: https://holzauge-fotografie.de
  - name: Vato Sikharulidze
    url: https://www.vatosikharulidze.com
  - name: Moritz Hagedorn
    url: https://moritzhagedorn.com
  - name: Malte van de Water
    url: https://maltevandewater.de
  - name: Intissar Belaid
    url: https://intissarbelaid.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://avatars.githubusercontent.com/u/6310388?s=460&u=1356e91c86aef3682d21c93d16147132446b5c36&v=4
  name: Status
  introTitle: "**Status** about different Pages i manage."
  introMessage: Website Status Overview
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
